<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container45uoyeg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container45uoyeg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container45uoyeg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container45uoyeg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container45uoyeg\appDevDebugProjectContainer(array(
    'container.build_hash' => '45uoyeg',
    'container.build_id' => 'e92b6424',
    'container.build_time' => 1538428660,
), __DIR__.\DIRECTORY_SEPARATOR.'Container45uoyeg');
